--select
SELECT FirstName, MiddleName, LastName
FROM Person.Person

SELECT COLUMN_NAME, DATA_TYPE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'Product'
ORDER BY ORDINAL_POSITION

SELECT StandardCost, ListPrice
FROM Production.Product


--where

SELECT ListPrice, StandardCost
FROM Production.Product
Where ListPrice > 500 and StandardCost >= 200
ORDER BY ListPrice ASC

SELECT COLUMN_NAME, DATA_TYPE 
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'Address'
ORDER BY ORDINAL_POSITION

SELECT City FROM Person.Address
ORDER BY City

--distinct

SELECT DISTINCT City
FROM Person.Address
ORDER BY City

--top

SELECT TOP 5 FirstName FROM Person.Person 


SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Product' ORDER BY ORDINAL_POSITION

SELECT TOP 20 Name, ProductNumber FROM Production.Product ORDER BY ProductNumber DESC

--aliases

SELECT Name as ProductNAME , Size as ProductSize 
From Production.Product

SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Product' ORDER BY ORDINAL_POSITION

SELECT COLUMN_NAME, DATA_TYPE FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Employee' ORDER BY ORDINAL_POSITION

SELECT TABLE_SCHEMA, TABLE_NAME
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_TYPE = 'BASE TABLE'
ORDER BY TABLE_SCHEMA

SELECT NationalIDNumber as NID, JobTitle as Designation FROM HumanResources.Employee